
example:
	scrapy crawl --set-json='DECAPTCHA_ENGINES=["decaptcha_example.example_engine.ExampleEngine"]' example

hackforums:
	scrapy crawl --set-json='DECAPTCHA_ENGINES=["decaptcha.engines.cloudflare.CloudflareEngine"]' hackforums.net	